######################################################################
# MSX PICOVERSE PROJECT
# (c) 2026 Cristiano Goncalves
# The Retro Hacker
#
# Makefile - build script for the MSX PICOVERSE 2350 Yamanooto tool
#
# This Makefile compiles the Yamanooto UF2 creator, regenerating the
# embedded Raspberry Pi Pico firmware header, and packages the executable.
######################################################################

PROJECT := 2350-yamanooto
include ../../../../scripts/native-tool.mk
