######################################################################
# MSX PICOVERSE PROJECT                                               
# (c) 2026 Cristiano Goncalves                                        
# The Retro Hacker                                                    
#                                                                      
# Makefile - build script for the MSX PICOVERSE 2040 loadROM tool    
#                                                                      
# This Makefile compiles the loadROM utility, regenerates the embedded 
# Raspberry Pi Pico firmware header, and packages the executable.      
######################################################################

PROJECT := 2040-loadrom
include ../../../../scripts/native-tool.mk
